# This is a basic workflow that is manually triggered

name: clay2

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# This workflow makes x86_64 binaries for mac, windows, and linux.


jobs:
  mac-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetos: [windows, darwin]
    name: clay2 for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env:
          GOOS: ${{ matrix.targetos }}

      - name: Compile
        run: |
          cd cmd/clay2d
          go build .
          cd ..
          cd clay2cli
          go build .

      - uses: actions/upload-artifact@v2
        with:
          name: clay2cli ${{ matrix.targetos }}
          path: cmd/clay2cli/clay2cli

      - uses: actions/upload-artifact@v2
        with:
          name: clay2d ${{ matrix.targetos }}
          path: cmd/clay2d/clay2d

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, riscv64, amd64]

    name: clay2 for ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env:
          GOARCH: ${{ matrix.arch }}

      - name: Compile
        run: |
          cd cmd/clay2d
          go build .
          cd ..
          cd clay2cli
          go build .

      - uses: actions/upload-artifact@v2
        with:
          name: clay2cli ${{ matrix.arch }}
          path: cmd/clay2cli/clay2cli

      - uses: actions/upload-artifact@v2
        with:
          name: clay2d ${{ matrix.arch }}
          path: cmd/clay2d/clay2d
